name: swa
description: A new Flutter project.
publish_to: 'SWA'

version: 1.2.2+17

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  #  webview_flutter: ^3.0.0
  cool_alert: ^2.0.1
  url_launcher: ^6.0.13
  flutter_svg: ^2.0.17
  sizer: ^3.0.5
  pdf: ^3.9.0 
  printing: ^5.4.2
  equatable:
  dartz:
  internet_connection_checker:
  shared_preferences:
  http:
  http_interceptor:
  flutter_bloc:
  flutter_device_type: ^0.4.0
  get_it:
  injectable:
  webview_flutter: ^4.4.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  dropdown_textfield: ^1.2.0
  flutter_spinkit: ^5.2.0
  pin_code_fields: ^8.0.1
  salomon_bottom_bar: ^3.3.2
  badges: ^3.1.2
  permission_handler: ^11.0.1
  google_api_availability: ^5.0.0
  qr_flutter: ^4.1.0
  flutter_timer_countdown: ^1.0.7
  circular_countdown_timer: ^0.2.3
  flutter_screenutil: ^5.9.3
  indexed: ^0.0.8
  dotted_line: ^3.2.3
  page_transition: ^2.1.0
  firebase_messaging: ^15.2.1
  firebase_core: ^3.10.1
  jhijri_picker: ^1.0.1
  flutter_localization: ^0.3.1
  intl: ^0.19.0
  scroll_loop_auto_scroll: ^0.0.5
book_my_seat:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_localizations:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/fonts/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/NeueHaasGrotesk-Bold.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/NeueHaasGrotesk-Regular.ttf
    - family: meduim
      fonts:
        - asset: assets/fonts/NeueHaasDisplayMediu.ttf
    - family: roman
      fonts:
        - asset: assets/fonts/NeueHaasDisplayRoman.ttf
    - family: black
      fonts:
        - asset: assets/fonts/NeueHaasGrotesk-Black.ttf

    - family: normal
      fonts:
        - asset: assets/fonts/NeueHaasGroteskBloomberg-2c86312d1d9514ad722de70db084b58a.ttf    

    - family: Arabic_Medium
      fonts:
        - asset: assets/fonts/arabic_medium.ttf

    - family: Arabic_Bold
      fonts:
        - asset: assets/fonts/arabic_bold.ttf

    - family: Arabic_Regular
      fonts:
        - asset: assets/fonts/arabic_regular.ttf       


#  fonts:
#    - family: English_Black
#      fonts:
#        - asset: assets/fonts/Poppins-Black.otf
#    - family: English_Bold
#      fonts:
#        - asset: assets/fonts/Poppins-Bold.otf
#    - family: English_Regular
#      fonts:
#        - asset: assets/fonts/Poppins-Regular.otf
#    - family: English_Medium
#      fonts:
#        - asset: assets/fonts/Poppins-Medium.otf
#
#    - family: Arabic_Medium
#      fonts:
#        - asset: assets/fonts/arabic_medium.ttf
#
#    - family: Arabic_Bold
#      fonts:
#        - asset: assets/fonts/arabic_bold.ttf
#
#    - family: Arabic_Regular
#      fonts:
#        - asset: assets/fonts/arabic_regular.ttf
