name: swa
description: A new Flutter project.
publish_to: 'SWA' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.6.0
  sizer: ^2.0.15
  equatable:
  dartz:
  internet_connection_checker:
  shared_preferences:
  http:
  http_interceptor:
  flutter_bloc:
  flutter_device_type:
  get_it:
  injectable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/NeueHaasGrotesk-Bold.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/NeueHaasGrotesk-Regular.ttf

#  fonts:
#    - family: English_Black
#      fonts:
#        - asset: assets/fonts/Poppins-Black.otf
#    - family: English_Bold
#      fonts:
#        - asset: assets/fonts/Poppins-Bold.otf
#    - family: English_Regular
#      fonts:
#        - asset: assets/fonts/Poppins-Regular.otf
#    - family: English_Medium
#      fonts:
#        - asset: assets/fonts/Poppins-Medium.otf
#
#    - family: Arabic_Medium
#      fonts:
#        - asset: assets/fonts/arabic_medium.ttf
#
#    - family: Arabic_Bold
#      fonts:
#        - asset: assets/fonts/arabic_bold.ttf
#
#    - family: Arabic_Regular
#      fonts:
#        - asset: assets/fonts/arabic_regular.ttf